### PR TITLE
fix issue #379

### PR DESCRIPTION
**Pull request by robstradling**

### CODE REVIEW

**Comment by mouse07410** [comment]
I tried to merge your PR into my fork https://github.com/mouse07410/asn1c.git, and it fails the CI. Some examples:
```
. . . . .
Checking ../../tests/tests-asn1c-compiler/102-class-ref-SE.asn1 against ../../tests/tests-asn1c-compiler/102-class-ref-SE.asn1.-EF
FATAL: Unknown type "REF-ID2" referenced by "REF-ID" at line 15 in ../../tests/tests-asn1c-compiler/102-class-ref-SE.asn1
FATAL: Unknown type "REF-ID" referenced by "REF-ID2" at line 17 in ../../tests/tests-asn1c-compiler/102-class-ref-SE.asn1
FATAL: Class field REF-ID.&id lookup at line 18 in something that is not a class: REF-ID2 at line 17 in ../../tests/tests-asn1c-compiler/102-class-ref-SE.asn1
FATAL: Unknown type "REF-ID.&id" referenced by "field" at line 18 in ../../tests/tests-asn1c-compiler/102-class-ref-SE.asn1
FATAL: Unknown type "REF-ID.&Type" referenced by "params" at line 20 in ../../tests/tests-asn1c-compiler/102-class-ref-SE.asn1
. . . . .
```

Here's the complete log: [test-suite.log.txt](https://github.com/vlm/asn1c/files/4823038/test-suite.log.txt)

I will consider merging it when it's clean wrt. CI.

Thanks!

**Comment by robstradling** [comment]
> @robstradling if you wish, you can rebase your PR against my fork, getting the CI to pass.

Do you mean I should open a new PR against your fork?  If not, please help me to understand exactly what you mean.  Thanks.

**Comment by mouse07410** [comment]
@robsttadling that's exactly what I meant. I'd appreciate if you could test my fork, and if it exhibits the same problem - rebase your fix against it. (Of course, we want to make sure CI stays happy.)

Thanks!

**Comment by robstradling** [comment]
@mouse07410 I've opened https://github.com/mouse07410/asn1c/pull/65.  Should I expect to see the CI failures on that page?

**Comment by mouse07410** [comment]
@robstradling yes and yes

**Comment by vlm** [comment]
Thank you, colleagues!

**Pull request merged**
