### PR TITLE
Optionally disable the use of alloca

### PR DESCRIPTION
**Pull request by craig65535**
I'm using asn1c in a project where a hard requirement is not using alloca. This pull request makes the use of alloca in the generated C files optional (but enabled by default).

I tried to follow the existing code style.

### CODE REVIEW

**Comment by craig65535** [comment]
@vlm not sure how to address the drop in code coverage. The new flag is set at configure-time.

**Comment by vlm** [comment]
Removed alloca throughout. Good riddance. Thank you for raising the issue!

**Comment by craig65535** [comment]
Thanks @vlm. Looking forward to the next release. Is there a plan for when 0.9.29 will be released?

**Comment by vlm** [comment]
I'll cut the next release when I fix OER SEQUENCE decoder leaking memory on failure (on invalid data). That's my only mandatory outstanding goal for the next release.

**Pull request closed without merging**
