### PR TITLE
Update configure.ac

### PR DESCRIPTION
**Pull request by brchiu**
fixing problem found when invoke autoreconf -iv where autoreconf is of version 2.69

### CODE REVIEW

**Comment by anatolyborodin** [comment]
Can #62 be related to this change?

**Comment by anatolyborodin** [comment]
@vlm #51 is also AM_PROG_AR-related.

**Comment by simo5** [comment]
This patch fixes autoreconf also on Fedora with automake 1.15

**Comment by DevNaga** [comment]
same problem on my ubuntu 14.04 LTS too.. Your patch fixes it .. i tried adding directly the AM_PROG_AR to configure.ac and it worked too.

**Pull request merged**
