### PR TITLE
per encoding allow larger constraints

### PR DESCRIPTION
**Pull request by persandstrom**
Constraint values might be larger than what can be held in a 32bit integer.
One example is TimestampIts defined by ETSI in http://forge.etsi.org/websvn/filedetails.php?repname=LIBS.LibIts&path=%2Ftrunk%2Fasn1%2FITS-Container%2FITS-Container.asn

### CODE REVIEW

**Comment by mouse07410** [comment]
1. Could you please fix the Travis complaints?
2. It would be great if in addition to the actual enhancement you could fix the tests, so that validation suite doesn't fail when your PR is applied/merged.

**Comment by persandstrom** [comment]
@mouse07410 Could you point me in the right direction to fix the last tests?

I have changed from c89 to c99 in order to get support for ```long long```.

**Comment by mouse07410** [comment]
> Could you point me in the right direction to fix the last tests?

Sure. In general, the idea is:

1. Apply your changes to your repo fork (which you must have already done, otherwise you wouldn't be producing PRs).
2. Run "make all && make check".
3. Observe where (on what tests and what test files) the validation suite fails.
4. Update the files in the validation/test suite that have this discrepancy between the old and the new way of dealing with PER.

P.S. I might be confused by other PER-related PRs. If asn1c validation suite runs fine on your changes as is - then all is good.

**Comment by persandstrom** [comment]
Thanks @mouse07410. I think the only remaining error now is the same as reported in issue https://github.com/vlm/asn1c/issues/130

**Comment by mouse07410** [comment]
> I think the only remaining error now is the same as reported in issue #130

You're welcome - but I do not think so. Travis https://travis-ci.org/vlm/asn1c/jobs/176035920 finds that the generated code differs from what it expects. Check the Travis output at the above URL, it's extremely unambiguous. Of course, the question is what test/validation files to correct - but that I'm leaving to you. :-)

**Comment by persandstrom** [comment]
Ah, I get it now! :+1:

**Comment by mouse07410** [comment]
Sure. Also, take a look at PR #125 - the author faced a similar problem, and addressed it.

:-)

**Comment by brchiu** [comment]
Hi, @mouse07410 & @persandstrom,

I fetched PR #125 to my local machine, compare to vlm's Aug 2 version, 
but I did not find file modification in grammar or parser part. 

Then I tried to process **99-class-sample-OK.asn1.-EFprint-class-matrix** using asn1c with PR #125 merged. I got the same error message :

```
ASN.1 grammar parse error near line 24 (token "BY"): syntax error, unexpected TOK_BY, expecting '}'
Cannot parse "99-class-sample-OK.asn1.-EFprint-class-matrix"
```
So I don't think PR 125 itself has addressed on this Travis CI problem.

**Comment by mouse07410** [comment]
@persandstrom I think you're on the right track. I like your changes. My only concern is that Travis CI is still unhappy with something (I confess that browsing the logs I couldn't immediately figure out why - most of the stuff there looks good). Please go through the Travis logs with a fine-tooth comb and try to locate & remedy the actual remaining problem(s).

For example, I don't think this is the cause of the Travis's unhappiness, but it pays to address it nonetheless:
```
. . . . .
Checking ../../tests/97-type-identifier-SW.asn1 against ../../tests/97-type-identifier-SW.asn1.-EF
WARNING: ASN.1 expression "TYPE-IDENTIFIER" at line 17 of module ASN1C-UsefulInformationObjectClasses
clashes with expression "TYPE-IDENTIFIER" at line 23 of module ModuleTypeIdentifier1 (../../tests/97-type-identifier-SW.asn1).
Rename or remove either instance to resolve the conflict in ../../skeletons/standard-modules/ASN1C-UsefulInformationObjectClasses.asn1
. . . . .
```

@brchiu I'm confused. You're referring to #125, while this is #129, presumably superseding it. And looking at the current Travis log, I see that `99-class-sample-OK.asn1` appears to be OK:
```
. . . . .
Checking ../../tests/98-attribute-class-OK.asn1 against ../../tests/98-attribute-class-OK.asn1.-P
Checking ../../tests/99-class-sample-OK.asn1 against ../../tests/99-class-sample-OK.asn1.-EFprint-class-matrix
PASS: check-parsing.sh
==================
All 2 tests passed
. . . . .
```

I don't think this error matters, because it seems to be expected:
```
. . . . .
[=> 129-enum-OK.asn1]
[=> 02-garbage-NP.asn1]
Expecting error...
ASN.1 grammar parse error near line 15 (token "garbage"): syntax error, unexpected TOK_identifier
Previous error is EXPECTED, no worry
[=> 34-class-OK.asn1]
. . . . .
```

**Comment by brchiu** [comment]
@mouse07410, I knew this is PR #129. I did this comparison because you advised @persandstrom to have a look at PR #125 in your comment, 
```
Also, take a look at PR #125 - the author faced a similar problem, and addressed it.
```
I looked into the Travis CI logs of both PR #125 and this PR #129. 

I knew PR #125's Travis CI log looks OK for **99-class-sample-OK.asn1.-EFprint-class-matrix**.

Since I am not able to know what happen on Travis CI server, a naive way is to do the same procedure, i.e. fetching asn1c trunk and applying PR #125 or PR #129 on **my local machine**. Then try to see how both asn1c executable files do with **99-class-sample-OK.asn1.-EFprint-class-matrix**.

Strangely, in contrast to PR #125's Travis CI log, it also failed to parse **99-class-sample-OK.asn1.-EFprint-class-matrix** as in PR #129's log. That's why I though this problem was not solved in #125.

Perhaps you can try it on your machine. Then we have a cross-comparison with different environments.

**Comment by velichkov** [comment]
The tests in PR #125 execute successfully for me on Debian 7 ( wheezy ) and RedHat EL7 (with b97d65a2b98c60b2784a7967f4d8e1f642d09eab applied)

And the `check-src/check-127.-gen-PER.c` test fails with 
```
make[4]: Entering directory `/home/vasko/asn1c/asn1c_github/build/asn1c/tests/test-check-127.-gen-PER'
gcc -DSRCDIR=../../../../asn1c/tests -I. -std=gnu99 -Wno-error=unused-variable -g -O2 -Wall -Wcast-qual -Wchar-subscripts -Wmissing-prototypes -Wmissing-declarations -Wno-error=cast-align -g -O0 -o check-executable *.c* -lm
T.c: In function ‘memb_full32range_constraint_1’:
T.c:252:33: error: expected ‘)’ before ‘LL’
  if((value >= (-2147483647L - 1)LL && value <= 2147483647LL)) {
                                 ^
```
and the contents of T.c is
```
238 static int
239 memb_full32range_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
240             asn_app_constraint_failed_f *ctfailcb, void *app_key) {
241     long long value;
242     
243     if(!sptr) {
244         ASN__CTFAIL(app_key, td, sptr,
245             "%s: value not given (%s:%d)",
246             td->name, __FILE__, __LINE__);
247         return -1;
248     }
249     
250     value = *(const long long *)sptr;
251     
252     if((value >= (-2147483647L - 1)LL && value <= 2147483647LL)) {
253         /* Constraint check succeeded */
254         return 0;

```

**Comment by mouse07410** [comment]
1. @brchiu by itself #125 passes all the validation checks. From that point of view, it is absolutely correct. I advised @persandstrom to look at it to see *how* that PR dealt with the need to modify validation suite *in addition* to changing the actual code (which he did very nicely). You misunderstood my recommendation. As for why #125 fails to parse something on *your* machine - I've no idea. Travis thinks it parses everything just like it is supposed to.
2. This PR still needs work, though it's much closer to being ready, IMHO. The problem seems to be putting of "LL" in the wrong place (thanks, @velichkov). I'm sure @persandstrom will find the cause and take care of it.

**Comment by brchiu** [comment]
@mouse07410, got it, thank you !

**Comment by persandstrom** [comment]
All tests pass at Travis now but there are still some that fails on my machine:

From ```asn1c/tests/test-check-127.-gen-PER/check-127.-gen-PER.c```:
```
      ti.small32range = -2000000000;                                               
      ti.full32range = (-2147483647L - 1);                                         
      ti.unsigned32 = 4000000000;                                                  
      ti.unsplit32 = 500;                                                          
      verify(3, &ti);   
```
Failes with: 
```
<T>
    <small32range>-1</small32range>
    <full32range>-1</full32range>
    <unsigned32>1</unsigned32>
    <unsplit32>300</unsplit32>
</T>
3 IN: { -2000000000, -2147483648, 4000000000, 500 }
check-executable: check-127.-gen-PER.c:24: verify: Assertion `er.encoded == 8 * sizeof(buf)' failed.
```
And I can't figure out why

**Comment by mouse07410** [comment]
> My guess is that the tests only succeeds on 64bit systems...

Hmm, interesting... Let me see how it behaves on my box (64-bit :)

**Comment by velichkov** [comment]
Hi @persandstrom,

> My guess is that the tests only succeeds on 64bit systems...

Yes that's correct, the test fails only on 32bit build

> And I can't figure out why

To get some more information configure the build with `--enable-ASN_DEBUG` flag.

```bash
./configure --enable-ASN_DEBUG --build=i686-linux-gnu CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32
make check
cd asn1c/tests/test-check-127.-gen-PER/
./check-executable
Encoding NativeInteger unsigned32 -294967296 (UPER) (NativeInteger.c:282)
Value 18446744073414584320 (00/9) lb 0 ub 4294967295 ext (INTEGER.c:705)
Failed to encode element unsigned32 (INTEGER.c:729)
Freeing INTEGER as a primitive type (asn_codecs_prim.c:125)
check-executable: check-127.-gen-PER.c:24: verify: Assertion `er.encoded == 8 * sizeof(buf)' failed.
```
From INTEGER.c
```
 724         if(ct->flags & APC_EXTENSIBLE) {
 725             if(per_put_few_bits(po, inext, 1))
 726                 ASN__ENCODE_FAILED;
 727             if(inext) ct = 0;
 728         } else if(inext) {
 729             ASN__ENCODE_FAILED;
 730         }
```
I don't quite understand this code.

The `test-check-03.-fwide-types` fails as well (32bit only)
```bash
cd asn1c/tests/test-check-03.-fwide-types
./check-executable 
INTEGER body 6 0x3c..0x3e (INTEGER.c:333)
Found "red" => 0 (INTEGER.c:414)
<red/> -> 0 == 0
Failed to encode element Enum2 (xer_encoder.c:37)
0 ->  == <Enum2><red/></Enum2>
check-executable: check-03.-fwide-types.c:47: check_xer: Assertion `0 == strcmp(buf, buf2)' failed.
```

**Comment by persandstrom** [comment]
I have figured out that it is large unsigned max values that get interpreted wrong. Probably max values that are larger than long-max but less than ulong-max.

**Comment by velichkov** [comment]
Hi @persandstrom,

In order to have both 32bit and 64bit builds in travis-ci could you add  the following to .travis.yml in your branch

```patch
diff --git a/.travis.yml b/.travis.yml
index 6e0f985..3c26404 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,9 +2,18 @@ language: c
 compiler:
   - gcc
   - clang
+env:
+  - BUILD=x86_64-linux-gnu
+    CFLAGS=-m64 LDFLAGS=-m64
+  - BUILD=i686-linux-gnu
+    CFLAGS=-m32 LDFLAGS=-m32
+addons:
+  apt:
+    packages:
+    - gcc-multilib
 script:
     - autoreconf -iv
-    - ./configure --enable-Werror
+    - ./configure --enable-Werror --build=$BUILD
     - make -j8
     - make check
     - make distcheck
```

**Comment by persandstrom** [comment]
@velichkov Thanks, I'll add that

**Comment by persandstrom** [comment]
All test pass now. 

Is there anything else I need to do?

Add new tests for 64bit integers? where should I add them in that case, test 127?

**Comment by mouse07410** [comment]
@persandstrom as far as I'm concerned, this PR is ready. You've done your work.

@vlm said he'd go through the PRs in a couple of weeks. I hope he would quickly merge at least these: #102, #104, #110, #126, #129.

**Comment by mouse07410** [comment]
@vlm, ping... Could you please take a look at these PRs and (hopefully) commit them?

**Comment by mouse07410** [comment]
I've started a fork, whose only/main purpose is having all the reasonable/relevant PRs applied: https://github.com/mouse07410/asn1c.git 

So that whoever needs an updated/fixed version doesn't have to apply all those PRs himself.

**Comment by Channakeshava** [comment]
Hi,

I used https://github.com/mouse07410/asn1c.git for integers which are more than 32 bits. I found asn1c compiler not adding range bits in asn_PER_memb_varianceLongitude_constr_9 function for below schema.

LocationStatistics ::= SEQUENCE {
   varianceLongitude INTEGER (0..9223372036854775807), 
   varianceLatitude INTEGER (0..9223372036854775807)
}

autogenerated code snippet:
static asn_per_constraints_t asn_PER_memb_varianceLongitude_constr_9 GCC_NOTUSED = {
        { APC_CONSTRAINED,       0, -1,  0,  9223372036854775807 }      /* (0..9223372036854775807) */,
        { APC_UNCONSTRAINED,    -1, -1,  0,  0 },
        0, 0    /* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_varianceLatitude_constr_10 GCC_NOTUSED = {
        { APC_CONSTRAINED,       0, -1,  0,  9223372036854775807 }      /* (0..9223372036854775807) */,
        { APC_UNCONSTRAINED,    -1, -1,  0,  0 },
        0, 0    /* No PER value map */
};

Correct code snippet should have been:
static asn_per_constraints_t asn_PER_memb_varianceLongitude_constr_9 GCC_NOTUSED = {
        { APC_CONSTRAINED,       63, -1,  0,  9223372036854775807 }      /* (0..9223372036854775807) */,
        { APC_UNCONSTRAINED,    -1, -1,  0,  0 },
        0, 0    /* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_varianceLatitude_constr_10 GCC_NOTUSED = {
        { APC_CONSTRAINED,       63, -1,  0,  9223372036854775807 }      /* (0..9223372036854775807) */,
        { APC_UNCONSTRAINED,    -1, -1,  0,  0 },
        0, 0    /* No PER value map */
};


Could you please look into this and address this issue ?

**Comment by persandstrom** [comment]
Hi, 
I'm currently not working with this, and it might be that I didn't need the larger constrains after all. 
If you are able to solve it you can a new PR to asn1c containing my changes and your additions to it and this one can be closed without being merged.

**Comment by mouse07410** [comment]
@Channakeshava can you please test the branch 115 of my fork, and report the results here?

**Comment by Channakeshava** [comment]
@mouse07410  I did test on the branch 115 but not successful. I could see range bits are not updated. I have copy pasted code snippet for your reference.

static asn_per_constraints_t asn_PER_memb_varianceLongitude_constr_9 GCC_NOTUSED = {
        { APC_CONSTRAINED,       0, -1,  0l, 9223372036854775807ull }  /* (0..9223372036854775807) */,
        { APC_UNCONSTRAINED,    -1, -1,  0,  0 },
        0, 0    /* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_varianceLatitude_constr_10 GCC_NOTUSED = {
        { APC_CONSTRAINED,       0, -1,  0l, 9223372036854775807ull }  /* (0..9223372036854775807) */,
        { APC_UNCONSTRAINED,    -1, -1,  0,  0 },
        0, 0    /* No PER value map */
}

**Comment by mouse07410** [comment]
@persandstrom you're probably in the best position to diagnose this problem. And off-hand it seems to be a simple omission case - some piece of code was supposed to insert constraint figure, but failed to do so. Could you please take a look...?

**Comment by mouse07410** [comment]
@Channakeshava The problem is worse than not adding constraints: when I'm testing your ASN.1 example, it does not produce PER output at all - neither APER nor UPER (see here https://github.com/mouse07410/asn1c/pull/1#issuecomment-288286455). 

@persandstrom do you have anything to suggest here?

**Comment by persandstrom** [comment]
I suggest that we remove this PR for now, or if someone else takes over. As I said previously I did not need this functionality after all and right now I can't prioritise it.

**Comment by vlm** [comment]
Holy crap, guys, it'll take me a few hours to read your thread ;) But thanks for caring!

**Comment by mouse07410** [comment]
> I suggest that we remove this PR for now, or if someone else takes over.

Unfortunately there's no one I'm aware of who's both able and willing to take over this PR. 

Therefore I will change the current master of https://github.com/mouse07410/asn1c.git to branch 129, and the current branch 115 (that implements support for wide PER constraints differently) will become the new master.

**Comment by ikarso** [comment]
@mouse07410 || @vlm what needs to be done to get this PR in shape for merge?
Integrate @velichkov commits and fix APER decode? 
I belive its more clean to fix this PR only for UPER. The APER part can be applied as a patch to #125 / #115

**Comment by mouse07410** [comment]
> @mouse07410 what needs to be done to get this PR in shape for merge?

It **was** merged into my master, but it turned out that this PR did not actually support wide(r) constraints for APER. And as you don't have time for it, I'd rather not maintain a master with code that is known to have problems with no fixes.

Therefore I will relegate it to a branch 129 (so it does not go away or disappear), but the master will be based on another APER implementation.

**Comment by momor10** [comment]
is this still not fixed? is it related to #303 ?

**Pull request closed without merging**
