### PR TITLE
Refreshing reserved keywords

### PR DESCRIPTION
**Pull request by gareins**
For c11 and c++14.

### CODE REVIEW

**Comment by anatolyborodin** [comment]
After rearranging the strings according to the original order, I got the following diff

```diff
--- libasn1compiler/asn1c_misc.c
+++ libasn1compiler/asn1c_misc.c
@@ -5,16 +5,19 @@
 #include <asn1fix_export.h>	/* other exportable stuff from libasn1fix */
 
 /*
- * Checks that the given string is not a reserved C/C++ keyword.
- * ISO/IEC 9899:1999 (C99), A.1.2
+ * Checks that the given string is not a reserved C/C++ keyword [1],[2].
+ * _* keywords not included, since asn1 identifiers cannot begin with hyphen [3]
+ * [1] ISO/IEC 9899:2011 (C11), 6.4.1
+ * [2] ISO/IEC 14882:2014 (C++14), 2.12
+ * [3] ISO/IEC 8824-1:2003 (asn1) 11.3
  */
 static char *res_kwd[] = {
+	/* C */
 	"auto", "break", "case", "char", "const", "continue", "default",
 	"do", "double", "else", "enum", "extern", "float", "for", "goto",
 	"if", "inline", "int", "long", "register", "restrict", "return",
 	"short", "signed", "sizeof", "static", "struct", "switch", "typedef",
 	"union", "unsigned", "void", "volatile", "while",
-	"_Bool", "_Complex", "_Imaginary",
 	/* C++ */
 	"class", "explicit", "bool", "mutable", 
 	"template", "typeid", "typename", "and", "and_eq", 
@@ -22,7 +25,16 @@ static char *res_kwd[] = {
 	"bitor", "compl", "bitand",
 	"const_cast", "dynamic_cast", "reinterpret_cast",
 	"static_cast", "true", "false", "namespace", "using",
-	"throw", "try", "catch"
+	"throw", "try", "catch",
+
+	"alignas", "alignof", "asm",
+	"char16_t", "char32_t",
+	"constexpr", "decltype", "delete", "delete",
+	"export", "friend", "new",
+	"noexcept", "nullptr", "operator",
+	"private", "protected", "public", "static_assert",
+	"this", "thread_local",
+	"virtual", "wchar_t"
 };
 static int
 reserved_keyword(const char *str) {
```

There are some new C++ keywords, but there were also 3 keywords removed. Why?

PS `"delete"` is duplicated.

**Comment by gareins** [comment]
Yeah, double delete is my mistake, 'delete' was the reason I did this change, so somehow I managed to put two of these in. But that is no excuse :)

About those three removed keywords, see the comment:
// _* keywords not included, since asn1 identifiers cannot begin with hyphen [3]
This means, that no asn valid identifies can be converted to asn1c identifier as _Bool, because asn1c just switches '-' -> '_' for identifiers (except for these reserved keywords).

How do I fix the double delete? Should I make a new pull request, or how are these things usually handled?

PS. also, why is the initial order better then alphabetical order?

**Comment by anatolyborodin** [comment]
> How do I fix the double delete? Should I make a new pull request, or how are these things usually handled?

Update your commit with `git commit --amend` or `git rebase`, push to your branch - and github should update the PR automatically.

**Comment by vlm** [comment]
Merged, thank you!

**Pull request merged**
